from peewee import *
import datetime
from random import randint, choice


db = SqliteDatabase('db/database.db')


class Component(Model):
    id = PrimaryKeyField(unique=True)
    article = IntegerField()
    title = CharField()
    maker = CharField()
    price = FloatField()
    amount = IntegerField()
    updated_date = DateTimeField()

    class Meta:
        database = db
        db_table = 'components'


data_makers = [
    {'maker': 'АвтоВАЗ', 'maker_ru': 'АвтоВАЗ'},
    {'maker': 'GAZ', 'maker_ru': 'ГАЗ'},
    {'maker': 'Камаз', 'maker_ru': 'Камаз'},
    {'maker': 'PAZ', 'maker_ru': 'ПАЗ'},
    {'maker': 'УАЗ', 'maker_ru': 'УАЗ'},
    {'maker': 'Hyundai', 'maker_ru': 'Хёндай'},
    {'maker': 'Renault', 'maker_ru': 'Рено'},
    {'maker': 'Volvo', 'maker_ru': 'Вольво'},
    {'maker': 'Bentley', 'maker_ru': 'Бэнтли'},
    {'maker': 'Jaguar', 'maker_ru': 'Ягуар'},
    {'maker': 'Rolls-Royce', 'maker_ru': 'Роллс-Ройс'},
    {'maker': 'Ford', 'maker_ru': 'Форд'},
    {'maker': 'Lexus', 'maker_ru': 'Лексус'},
    {'maker': 'Mazda', 'maker_ru': 'Мазда'},
    {'maker': 'Mitsubishi', 'maker_ru': 'Митсубиси'},
    {'maker': 'Nissan', 'maker_ru': 'Ниссан'},
    {'maker': 'Subaru', 'maker_ru': 'Субару'},
    {'maker': 'Suzuki', 'maker_ru': 'Сузуки'},
    {'maker': 'Toyota', 'maker_ru': 'Тойота'},
    {'maker': 'Yamaha', 'maker_ru': 'Ямаха'},
    {'maker': 'Ferrari', 'maker_ru': 'Феррари'},
    {'maker': 'Lamborghini', 'maker_ru': 'Ламборджини'},
    {'maker': 'Maserati', 'maker_ru': 'Мазератти'},
    {'maker': 'Opel', 'maker_ru': 'Опель'},
    {'maker': 'BMW', 'maker_ru': 'БМВ'},
    {'maker': 'Mercedes-Benz', 'maker_ru': 'Мерседес-Бенз'},
    {'maker': 'Porsche', 'maker_ru': 'Порш'},
    {'maker': 'Volkswagen', 'maker_ru': 'Фольксваген'},
    {'maker': 'Audi', 'maker_ru': 'Ауди'},
    {'maker': 'Peugeot', 'maker_ru': 'Пежо'},
    {'maker': 'Skoda', 'maker_ru': 'Шкода'},
    {'maker': 'Haval', 'maker_ru': 'Хаваль'},
    {'maker': 'БелАЗ', 'maker_ru': 'БелАЗ'}
]


data_components = [
    {'title': 'Амперметр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Клинометр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Динамометр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Указатель уровня топлива', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Манометр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Генератор переменного тока', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Аккумулятор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тюнер', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Сабвуфер', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Видеоплеер', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Панель защиты от проникновения', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Наружная дверная ручка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Внутренняя дверная ручка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Двигатель стеклоподъемника', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Модуль управления дверью', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Уплотнитель двери', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Поддержка сердечника радиатора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Коромысло', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Багажник на крышу', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Якорь', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выпускной патрубок', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная накладка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная накладка заднего хода', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Канал охлаждения тормозов', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной диск', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная жидкость', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной барабан', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная накладка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная колодка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Педаль тормоза', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной поршень', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной крен', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной ротор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной сервопривод', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Радиатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шланг охлаждающей жидкости (хомут)', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вентилятор охлаждения', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Лопасть вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ремень вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ремень вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Муфта вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный фильтр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляная прокладка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный поддон', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Маслопровод', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный фильтр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный всасывающий фильтр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка выпускного коллектора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выхлопная труба', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Теплозащитный экран', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Термоусадочные рукава и скотч', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Резонатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Глушитель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Каталитический нейтрализатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Хомут и скоба выхлопной трубы', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка выпускного фланца', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка выхлопной трубы', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выпускной коллектор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Форсунка топливной форсунки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливопровод', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливный насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка топливного насоса', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Регулятор давления топлива', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливная рейка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливный водоотделитель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливный водоотделитель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Впускной коллектор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка впускного коллектора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Система LPG (сжиженный нефтяной газ) в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Корпус дроссельной заслонки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ось', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шаровой шарнир', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ось балки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг развала', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг холостого хода', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Боковая ссылка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Стержень Panhard', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рука Питмана', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рука Питмана', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Узел и компонент усилителя рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Конец стойки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Амортизатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шпиндель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Стабилизаторы поперечной устойчивости и ссылка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Коробка рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Насос рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рулевая колонка в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Регулируемая педаль', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Полуось', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Корпус колокола', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Универсальный шарнир', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Другие ремни', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Держатель в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Цепное колесо и звездочка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Сцепление в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Трос сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Диск сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Диск сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вентилятор сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вилка сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шланг сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Накладка сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Коробка передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Холостая передача', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Кулак', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Главный цилиндр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выходной вал', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шестерня', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Планетарный редуктор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Карданный вал (приводной вал, карданный вал)', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тросик переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вилка переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ручка переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рабочий цилиндр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Редуктор скорости', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Амперметр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Клинометр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Динамометр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Указатель уровня топлива', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Манометр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Генератор переменного тока', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Аккумулятор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тюнер', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Сабвуфер', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Видеоплеер', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Панель защиты от проникновения', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Наружная дверная ручка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Внутренняя дверная ручка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Двигатель стеклоподъемника', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Модуль управления дверью', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Уплотнитель двери', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Поддержка сердечника радиатора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Коромысло', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Багажник на крышу', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Якорь', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Выпускной патрубок', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная накладка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная накладка заднего хода', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Канал охлаждения тормозов', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной диск', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная жидкость', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной барабан', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная накладка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозная колодка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Педаль тормоза', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной поршень', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной крен', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной ротор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тормозной сервопривод', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Радиатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шланг охлаждающей жидкости (хомут)', 'maker_id': randint(0, len(data_makers)),
     'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вентилятор охлаждения', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Лопасть вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ремень вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(
    300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ремень вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Муфта вентилятора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный фильтр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляная прокладка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный поддон', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Маслопровод', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(
        300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный фильтр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Масляный всасывающий фильтр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка выпускного коллектора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выхлопная труба', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Теплозащитный экран', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Термоусадочные рукава и скотч', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Резонатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Глушитель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Каталитический нейтрализатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Хомут и скоба выхлопной трубы', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка выпускного фланца', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка выхлопной трубы', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выпускной коллектор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Форсунка топливной форсунки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливопровод', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливный насос', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка топливного насоса', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Регулятор давления топлива', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливная рейка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливный водоотделитель', 'maker_id': randint(0, len(data_makers)), 'price': randint(
        300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Топливный водоотделитель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Впускной коллектор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Прокладка впускного коллектора', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Система LPG (сжиженный нефтяной газ) в сборе', 'maker_id': randint(0, len(data_makers)),
     'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Корпус дроссельной заслонки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ось', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Шаровой шарнир', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ось балки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг развала', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг холостого хода', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Боковая ссылка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Стержень Panhard', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рука Питмана', 'maker_id': randint(0,
                                                                                               len(data_makers)), 'price': randint(
        300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рука Питмана', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Узел и компонент усилителя рулевого управления', 'maker_id': randint(0, len(data_makers)),
     'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Конец стойки', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Амортизатор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шпиндель', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Стабилизаторы поперечной устойчивости и ссылка', 'maker_id': randint(0, len(data_makers)),
     'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0,
                                                                                                            20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Коробка рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Насос рулевого управления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рулевая колонка в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Регулируемая педаль', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Полуось', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Корпус колокола', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Универсальный шарнир', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Другие ремни', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Держатель в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Цепное колесо и звездочка', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Сцепление в сборе', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Трос сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Диск сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(
        300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Диск сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вентилятор сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вилка сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шланг сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Накладка сцепления', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Коробка передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Холостая передача', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Кулак', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Главный цилиндр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Выходной вал', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Шестерня', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000), 'amount': randint(0, 20),
     'updated_date': datetime.datetime.now()},
    {'title': 'Планетарный редуктор', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Карданный вал (приводной вал, карданный вал)', 'maker_id': randint(0, len(data_makers)),
     'price': randint(300, 10000), 'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Тросик переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Вилка переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Ручка переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рычаг переключения передач', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Рабочий цилиндр', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()},
    {'title': 'Редуктор скорости', 'maker_id': randint(0, len(data_makers)), 'price': randint(300, 10000),
     'amount': randint(0, 20), 'updated_date': datetime.datetime.now()}
]

# получение списка названий деталей БЕЗ ДУБЛЕЙ
components_list = []
for item in data_components:
    components_list.append(item['title'])
components_list = list(set(components_list))

# получение списка производителей БЕЗ ДУБЛЕЙ
makers_list = []
for item in data_makers:
    makers_list.append(item['maker'])
makers_list = list(set(makers_list))

# db.create_tables([Component])

data_components = []
for i in range(0, 200):
    component_dict = {
        'article': randint(10000, 99999),
        'title': choice(components_list),
        'maker': choice(makers_list),
        'price': randint(700, 10000),
        'amount': randint(3, 25),
        'updated_date': datetime.datetime.now()
    }
    data_components.append(component_dict)
# Component.insert_many(data_components).execute()

